version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: nest-api
    ports:
      - "3000:8000"
    env_file:
      - ./apps/api/.env
    networks:
      - app-network
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: react-client
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
